# Generated by Django 4.1.2 on 2022-10-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmember',
            name='access_level',
            field=models.CharField(choices=[('A', 'Owner'), ('B', 'Member')], default='B', max_length=1),
        ),
    ]
