# Generated by Django 4.1.2 on 2022-12-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_member', '0007_alter_taskmember_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmember',
            name='access_level',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
