# Generated by Django 4.1.2 on 2022-10-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_alter_calenderpost_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calenderpost',
            name='status',
        ),
        migrations.AddField(
            model_name='calenderpost',
            name='task_status',
            field=models.CharField(choices=[('A', 'In progress'), ('B', 'Idle'), ('C', 'Done')], default='B', max_length=1),
        ),
    ]
