# Generated by Django 4.1.2 on 2022-10-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0004_remove_calenderpost_status_calenderpost_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calenderpost',
            name='owner',
        ),
    ]
