# Generated by Django 4.1.2 on 2022-11-26 11:05

import calender.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0006_calenderpost_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderpost',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[calender.models.CalenderPost.validate_date]),
            preserve_default=False,
        ),
    ]
