# Generated by Django 4.1.2 on 2022-11-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0007_alter_calenderpost_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderpost',
            name='task_status',
            field=models.CharField(choices=[('IN PROGRESS', 'In progress'), ('IDLE', 'Idle'), ('DONE', 'Done')], default='IDLE', max_length=20),
        ),
    ]
